In [1]:
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision import transforms, utils
import torch.nn as nn
import torch.optim as optim
import os
from PIL import Image
import matplotlib.pyplot as plt
from img2vec_pytorch import Img2Vec
import timm
from tqdm.notebook import tqdm
%matplotlib inline

In [2]:
class AgarIoImagesLoader(DataLoader):
    def __init__(self, history_len =5):
        self.images

In [3]:
history_len = 10

In [4]:
class RNNRegression(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(RNNRegression, self).__init__()
        self.hidden_size = hidden_size
        self.rnn = nn.RNN(input_size, hidden_size, batch_first=True)
        self.fc = nn.Linear(hidden_size, output_size)
    
    def forward(self, x):
        out, _ = self.rnn(x)
        out = self.fc(out[:, -1, :])  # Take the last time step's output
        return out
    
class Embeddings(torch.nn.Module):
    def __init__(self, num_encoder_features = 512):
        super().__init__()
        self.encoder = timm.create_model('mobilenetv3_small', num_encoder_features)
        
    def forward(self, x):
        return self.encoder(x)
    
class HistoryEmbedding(torch.nn.Module):
    def __init__(self, num_encoder_features = 512, history_len = 10):
        super().__init__()
        self.history_len = history_len
        self.num_encoder_features = num_encoder_features
        self.encoder = timm.create_model('resnet18', num_classes=num_encoder_features)
        self.regressor = RNNRegression(num_encoder_features, self.history_len, 3)
        
    def forward(self, x):
        x = torch.stack([self.encoder(x[:,i,:,:,:]) for i in range(self.history_len)]).view(-1, self.history_len, self.num_encoder_features)
        return self.regressor(x)

In [5]:
class CustomImageDataset(Dataset):
    def __init__(self, data_dir,history_len, transform=None):
        
        self.num_images_per_folder = 1000
        self.num_folders = 10
        self.history_len = history_len
        self.dataset_length = self.num_images_per_folder * self.num_folders
        self.data_dir = data_dir
        self.transform = transform

    def __len__(self):
        return self.dataset_length

    def __getitem__(self, idx):
        img_in_folder_idx = idx % self.num_images_per_folder
        folder_idx = idx // self.num_images_per_folder
        images = []
        actions = []
        
        for i in range(img_in_folder_idx - self.history_len +1, img_in_folder_idx+1):
            if(i < 0):
                images.append(np.zeros((224,224,3), dtype=np.uint8))
                actions.append(np.zeros((3), dtype=np.float32))
            else:
                img = Image.open(os.path.join(self.data_dir, f'episode_{folder_idx}','image', f'{i}.jpg'))
                images.append(np.array(img))
                actions.append(np.load(os.path.join(self.data_dir, f'episode_{folder_idx}','arr', f'{i}.npy'),allow_pickle=True)[0]['action'])
            
        if self.transform:
            for i in range(len(images)):
                images[i] = self.transform(images[i])
                actions[i] = torch.from_numpy(actions[i])
        images = torch.stack(images)
        # In this example, we're just returning images without labels. 
        # You would typically also return labels in a real-world scenario.
        actions = actions[-1].float()
        return images, actions

In [6]:
def plot_sample(data):
    fig, axs = plt.subplots(1, history_len, figsize=(20, 20))
    for i in range(history_len):
        axs[i].imshow(data[0][i].permute(1, 2, 0))

In [7]:
transform = transforms.Compose([transforms.ToTensor(), transforms.Resize((224,224)),transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])
dataset = CustomImageDataset('data', history_len=history_len, transform=transform)

In [8]:
data_loader = DataLoader(dataset, batch_size=16, shuffle=True, num_workers=8)

In [9]:
model = HistoryEmbedding()

In [10]:
torch.cuda.is_available()

True

In [21]:
loss_function = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)  # You can use other optimizers like SGD if desired
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
moedl = model.to(device)
# Number of epochs
num_epochs = 10

for epoch in range(num_epochs):
    model.train()  # Set the model to training mode
    total_loss = 0.0
    
    for batch_data, batch_labels in tqdm(data_loader):
        # Transfer data and labels to GPU if one is available
        
        batch_data = batch_data.to(device)
        batch_labels = batch_labels.to(device)


        # 2. Training Loop
        optimizer.zero_grad()  # Zero the gradients
        
        predictions = model(batch_data)  # Get predictions from the model
        
        loss = loss_function(predictions, batch_labels)  # Compute the loss
        loss.backward()  # Backpropagate the loss
        optimizer.step()  # Update the model parameters
        
        total_loss += loss.item()  # Accumulate loss for monitoring
    
    # Print the average loss for this epoch
    avg_loss = total_loss / len(data_loader)
    print(f"Epoch [{epoch + 1}/{num_epochs}], Loss: {avg_loss:.4f}")

  0%|          | 0/625 [00:00<?, ?it/s]

In [12]:
#saving model
torch.save(model.state_dict(), 'model.pth')

In [13]:
model2 = HistoryEmbedding()

In [14]:
model2.load_state_dict(torch.load("model.pth"))

<All keys matched successfully>

In [15]:
def inference_model(img_sequence, model):
    # preprocessing input
    transform = transforms.Compose([transforms.ToTensor(), transforms.Resize((224,224)),transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])])
    input = []
    for img in img_sequence:
        input.append(transform(img).float())
    input = torch.stack(input).unsqueeze(0)
    input = input.to(device)
    # inference                               
    model.eval()
    with torch.no_grad():
        # print(img_sequence.shape)
        output = model(input)
        return output.cpu().numpy()

In [20]:
# testing an agent
from agar.Config import Config
from agar.Env import AgarEnv
import time
class Args:
    def __init__(self):
        self.num_controlled_agent = num_agents
        self.num_processes = 64
        self.action_repeat = 1
        self.total_step = 1e8
        self.r_alpha = 0.1
        self.r_beta = 0.1
        self.seed = 42
        self.gamma = 0.99
        self.eval = True
render = True
num_agents = 1

config = Config()
env = AgarEnv(Args())
env.reset()
num_iterations = 400
env.step([0,0,0])
imgs = [np.zeros([224,224,3]) for i in range(history_len)]

with torch.no_grad():
    for i in range(num_iterations):
        image = env.render(0, mode="rgb_array", render_player=False)
        print(image.shape)
        imgs.append(image.copy())
        imgs.pop(0)
        action = inference_model(imgs, model)
        print(action)
        action = action.reshape(-1)
        action[2] = 1 if action[2] > 0.5 else 0
        env.render(0, render_player=True)
        observations, rewards, done, info, new_obs = env.step(action)
        time.sleep(0.01)
        
env.close()

(800, 800, 3)
[[-8.8330299e-02 -3.3349384e-02  3.1739473e-05]]
(800, 800, 3)
[[-8.8324279e-02 -3.3347148e-02  2.8431416e-05]]
(800, 800, 3)
[[-8.8324934e-02 -3.3347387e-02  2.8789043e-05]]
(800, 800, 3)
[[-8.833006e-02 -3.334928e-02  3.159046e-05]]
(800, 800, 3)
[[-8.8320017e-02 -3.3345584e-02  2.6091933e-05]]
(800, 800, 3)
[[-8.8328898e-02 -3.3348862e-02  3.0964613e-05]]
(800, 800, 3)
[[-8.8323623e-02 -3.3346925e-02  2.8073788e-05]]
(800, 800, 3)
[[-8.8323772e-02 -3.3346970e-02  2.8163195e-05]]
(800, 800, 3)
[[-8.8324517e-02 -3.3347238e-02  2.8565526e-05]]
(800, 800, 3)
[[-8.8317722e-02 -3.3344764e-02  2.4855137e-05]]
(800, 800, 3)
[[-8.8323146e-02 -3.3346731e-02  2.7805567e-05]]
(800, 800, 3)
[[-8.8318765e-02 -3.3345137e-02  2.5421381e-05]]
(800, 800, 3)
[[-8.8325232e-02 -3.3347521e-02  2.8952956e-05]]
(800, 800, 3)
[[-8.8323474e-02 -3.3346850e-02  2.7999282e-05]]
(800, 800, 3)
[[-8.8324100e-02 -3.3347089e-02  2.8327107e-05]]
(800, 800, 3)
[[-8.8326722e-02 -3.3348072e-02  2.9787421e-

KeyboardInterrupt: 

In [48]:
env.close()